// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsTGV_AgYtIkM7KTOUttZclgcvCH1oRQQ',
    appId: '1:421162570630:web:8376a4ff191609cb681207',
    messagingSenderId: '421162570630',
    projectId: 'cryptocode-app-josevbrito',
    authDomain: 'cryptocode-app-josevbrito.firebaseapp.com',
    storageBucket: 'cryptocode-app-josevbrito.appspot.com',
    measurementId: 'G-6J5BNPZWC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz9PQcw4qPdlHydOBzvMsQyehUFy57pZk',
    appId: '1:421162570630:android:111981a4797bd022681207',
    messagingSenderId: '421162570630',
    projectId: 'cryptocode-app-josevbrito',
    storageBucket: 'cryptocode-app-josevbrito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXu7R222a3H1JBk0xg6j11vYcSQc5T1cg',
    appId: '1:421162570630:ios:77971b1bb49d18e8681207',
    messagingSenderId: '421162570630',
    projectId: 'cryptocode-app-josevbrito',
    storageBucket: 'cryptocode-app-josevbrito.appspot.com',
    iosBundleId: 'com.example.cryptocodeApp',
  );
}
